# Generated by Django 3.0.5 on 2020-04-01 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=40)),
                ('text', models.TextField()),
                ('link_code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('lang', models.CharField(choices=[('text', 'None'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('java', 'Java'), ('js', 'JavaScript'), ('php', 'PHP'), ('py', 'Python'), ('sql', 'SQL')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
