# Generated by Django 3.0.7 on 2020-07-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip_app', '0002_auto_20200624_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='snip',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
