# Generated by Django 3.0.6 on 2021-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip_app', '0002_auto_20210105_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snip',
            name='lang',
            field=models.CharField(choices=[('text', 'None'), ('Markup', 'markup'), ('html', 'html'), ('CSS', 'css'), ('C-like', 'clike'), ('JavaScript', 'javascript, js'), ('Arduino', 'arduino'), ('Bash', 'bash, shell'), ('BASIC', 'basic'), ('C', 'c'), ('C#', 'csharp, cs, dotnet'), ('Cpp', 'cpp'), ('CoffeeScript', 'coffeescript, coffee'), ('CMake', 'cmake'), ('Clojure', 'clojure'), ('Django/Jinja2', 'django, jinja2'), ('Docker', 'docker, dockerfile'), ('Git', 'git'), ('GameMaker Language', 'gml, gamemakerlanguage'), ('Go', 'go'), ('GraphQL', 'graphql'), ('Groovy', 'groovy'), ('Haml', 'haml'), ('HTTP', 'http'), ('Icon', 'icon'), ('Java', 'java'), ('JavaDoc', 'javadoc'), ('JSDoc', 'jsdoc'), ('JSON', 'json'), ('JSONP', 'jsonp'), ('JSON5', 'json5'), ('Kotlin', 'kotlin'), ('LaTeX', 'latex, tex, context'), ('Latte', 'latte'), ('Less', 'less'), ('LiveScript', 'livescript'), ('Lua', 'lua'), ('Makefile', 'makefile'), ('Markdown', 'markdown, md'), ('MATLAB', 'matlab'), ('nginx', 'nginx'), ('Objective-C', 'objectivec'), ('OpenCL', 'opencl'), ('Parser', 'parser'), ('Pascal', 'pascal, objectpascal'), ('Perl', 'perl'), ('PHP', 'php'), ('PL/SQL', 'plsql'), ('PowerShell', 'powershell'), ('Pug', 'pug'), ('Python', 'python, py'), ('R', 'r'), ('React JSX', 'jsx'), ('React TSX', 'tsx'), ('Regex', 'regex'), ('Ruby', 'ruby, rb'), ('Rust', 'rust'), ('SAS', 'sas'), ('Sass (Sass)', 'sass'), ('Sass (Scss)', 'scss'), ('Scala', 'scala'), ('SQL', 'sql'), ('Stylus', 'stylus'), ('Swift', 'swift'), ('Twig', 'twig'), ('TypeScript', 'typescript, ts'), ('Velocity', 'velocity'), ('vim', 'vim'), ('Visual Basic', 'visual-basic, vb'), ('Wiki markup', 'wiki'), ('YAML', 'yaml, yml'), ('Zig', 'zig')], default='text', max_length=18),
        ),
    ]
