# Generated by Django 3.0.7 on 2020-07-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snip_app', '0003_snip_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snip',
            name='private',
        ),
    ]
